// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package rand_go_gx are Go bindings to the GX package:
// github.com/gx-org/gx/tests/bindings/rand.
//
// Automatically generated by
// gx/golang/binder/gobindings/bindings.go.tmpl.
package rand_go_gx

import (
	"fmt"
	"reflect"
	"strings"

	"github.com/gx-org/backend/platform"
	"github.com/gx-org/gx/api"
	"github.com/gx-org/gx/api/values"
	"github.com/gx-org/gx/build/ir"
	"github.com/gx-org/gx/golang/binder/gobindings/types"
	"github.com/gx-org/gx/interp"
	"github.com/gx-org/gx/interp/state"
	_ "github.com/gx-org/gx/tests/bindings/rand"
	"github.com/pkg/errors"

	gxdep0 "github.com/gx-org/gx/stdlib/bindings/go/rand_go_gx"
)

// Force some package dependencies.
var (
	_ = fmt.Println
	_ = strings.Compare
	_ = reflect.TypeFor[int]
	_ = values.Struct{}
	_ = errors.Errorf
	_ = types.NewSlice[types.Bridger]
	_ = platform.HostTransfer
)

// PackageIR is the GX package intermediate representation
// built for a given runtime, but not yet for a specific device.
type PackageIR struct {
	Runtime *api.Runtime
	IR      *ir.Package
	Tracer  state.Tracer

	gxdep0 *gxdep0.PackageIR
}

// Load the GX package for a given backend.
func Load(rtm *api.Runtime) (*PackageIR, error) {
	bpkg, err := rtm.Builder().Build("github.com/gx-org/gx/tests/bindings/rand")
	if err != nil {
		return nil, err
	}
	pkg := &PackageIR{
		Runtime: rtm,
		IR:      bpkg.IR(),
	}

	if pkg.gxdep0, err = gxdep0.Load(rtm); err != nil {
		return nil, err
	}

	return pkg, nil
}

// BuildFor loads the GX package github.com/gx-org/gx/tests/bindings/rand
// then returns that package for a given device and options.
func BuildFor(dev *api.Device, options ...interp.PackageOptionFactory) (*Package, error) {
	pkg, err := Load(dev.Runtime())
	if err != nil {
		return nil, err
	}
	return pkg.BuildFor(dev, options...), nil
}

// Factory create new instance of types used in the package.
// The compiler associated with the factory defines on what
// device and with which options methods of the instances
// created by the factory are compiled for.
type Factory struct {
	Package *Package
}

// Package is a GX package for a given device.
// Functions and methods are compiled specifically for that device.
type Package struct {
	Package *PackageIR
	Device  *api.Device
	Factory *Factory

	options []interp.PackageOption

	gxdep0 *gxdep0.Package

	New        New
	Sample     Sample
	SampleBool SampleBool
}

// AppendOptions appends options to the compiler.
func (cmpl *Package) AppendOptions(options ...interp.PackageOptionFactory) {
	plat := cmpl.Package.Runtime.Backend().Platform()
	for _, opt := range options {
		cmpl.options = append(cmpl.options, opt(plat))
	}
}

// BuildFor returns a package ready to compile for a device and options.
func (pkg *PackageIR) BuildFor(dev *api.Device, options ...interp.PackageOptionFactory) *Package {
	c := &Package{
		Package: pkg,
		Device:  dev,
	}
	c.Factory = &Factory{Package: c}
	c.AppendOptions(options...)

	c.New = New{
		methodBase: methodBase{
			pkg:      c,
			function: c.Package.IR.Funcs[0].(*ir.FuncDecl),
		},
	}
	c.Sample = Sample{
		methodBase: methodBase{
			pkg:      c,
			function: c.Package.IR.Funcs[1].(*ir.FuncDecl),
		},
	}
	c.SampleBool = SampleBool{
		methodBase: methodBase{
			pkg:      c,
			function: c.Package.IR.Funcs[2].(*ir.FuncDecl),
		},
	}

	c.gxdep0 = c.Package.gxdep0.BuildFor(dev, options...)

	return c
}

type methodBase struct {
	pkg      *Package
	function ir.Func
	runner   *state.CompiledGraph
}

// New compiles and runs the GX function New for a device.
// New returns a new Rand instance given a seed.
type New struct {
	methodBase
}

// Sample compiles and runs the GX function Sample for a device.
// Sample the first few numbers from a number generator.
type Sample struct {
	methodBase
}

// SampleBool compiles and runs the GX function SampleBool for a device.
// Sample the first few booleans from a number generator.
type SampleBool struct {
	methodBase
}

// Run first compiles New for a given device and the given arguments.
// Once compiled, the function is then run with these same arguments.
// If the shape of the arguments change, the function will panic.
func (f *New) Run(arg0 types.Atom[int64]) (_ *gxdep0.Rand, err error) {
	var args []values.Value = []values.Value{
		arg0.Bridge().GXValue(), // seed int64
	}
	if f.runner == nil {
		f.runner, err = interp.Compile(f.pkg.Device, f.function.(*ir.FuncDecl), nil, args, f.pkg.options)
		if err != nil {
			return
		}
	}
	var outputs []values.Value
	outputs, err = f.runner.Run(nil, args, f.pkg.Package.Tracer)
	if err != nil {
		return
	}

	cmpl := f.pkg
	var out0 *gxdep0.Rand
	out0, err = cmpl.gxdep0.MarshalRand(outputs[0])
	if err != nil {
		return
	}

	return out0, nil
}

// Run first compiles Sample for a given device and the given arguments.
// Once compiled, the function is then run with these same arguments.
// If the shape of the arguments change, the function will panic.
func (f *Sample) Run(arg0 types.Atom[int64]) (_ types.Array[float32], err error) {
	var args []values.Value = []values.Value{
		arg0.Bridge().GXValue(), // seed int64
	}
	if f.runner == nil {
		f.runner, err = interp.Compile(f.pkg.Device, f.function.(*ir.FuncDecl), nil, args, f.pkg.options)
		if err != nil {
			return
		}
	}
	var outputs []values.Value
	outputs, err = f.runner.Run(nil, args, f.pkg.Package.Tracer)
	if err != nil {
		return
	}

	out0Value, ok := outputs[0].(values.Array)
	if !ok {
		err = errors.Errorf("cannot cast %T to %s", outputs[0], reflect.TypeFor[*values.DeviceArray]().Name())
		return
	}
	out0 := types.NewArray[float32](out0Value)

	return out0, nil
}

// Run first compiles SampleBool for a given device and the given arguments.
// Once compiled, the function is then run with these same arguments.
// If the shape of the arguments change, the function will panic.
func (f *SampleBool) Run(arg0 types.Atom[int64]) (_ types.Array[bool], err error) {
	var args []values.Value = []values.Value{
		arg0.Bridge().GXValue(), // seed int64
	}
	if f.runner == nil {
		f.runner, err = interp.Compile(f.pkg.Device, f.function.(*ir.FuncDecl), nil, args, f.pkg.options)
		if err != nil {
			return
		}
	}
	var outputs []values.Value
	outputs, err = f.runner.Run(nil, args, f.pkg.Package.Tracer)
	if err != nil {
		return
	}

	out0Value, ok := outputs[0].(values.Array)
	if !ok {
		err = errors.Errorf("cannot cast %T to %s", outputs[0], reflect.TypeFor[*values.DeviceArray]().Name())
		return
	}
	out0 := types.NewArray[bool](out0Value)

	return out0, nil
}
