// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpevelements

import (
	"go/ast"

	"github.com/gx-org/gx/build/fmterr"
	"github.com/gx-org/gx/build/ir"
)

type (
	// MacroElement is an element generated by calling a macro implementation.
	MacroElement interface {
		ir.Element
		Macro() *Macro
	}

	// FuncASTBuilder builds GX functions programmatically.
	FuncASTBuilder interface {
		MacroElement
		BuildDecl() (*ast.FuncDecl, bool)
		BuildBody(ir.Fetcher, ir.Func) (*ast.BlockStmt, []*SyntheticFuncDecl, bool)
	}

	// FuncAnnotator builds a synthetic function.
	FuncAnnotator interface {
		MacroElement
		Annotate(fmterr.ErrAppender, ir.PkgFunc) bool
	}

	// SyntheticFuncDecl is a synthetic package function declaration.
	SyntheticFuncDecl struct {
		Builder FuncASTBuilder
		F       *ast.FuncDecl
	}
)

// CoreMacroElement is a helper structure to implement macros.
type CoreMacroElement struct {
	Mac *Macro
}

var _ MacroElement = (*CoreMacroElement)(nil)

// Type returns the type of a macro function.
func (CoreMacroElement) Type() ir.Type {
	return ir.UnknownType()
}

// Macro returns the macro function that has generated this macro element.
func (m *CoreMacroElement) Macro() *Macro {
	return m.Mac
}
