//go:cgo_ldflag "-labsl_status"
//go:cgo_ldflag "-labsl_statusor"
// Code generated by cmd/cgo; DO NOT EDIT.

package cgx

import "unsafe"

import "syscall"

import _cgopackage "runtime/cgo"

type _ _cgopackage.Incomplete
var _ syscall.Errno
func _Cgo_ptr(ptr unsafe.Pointer) unsafe.Pointer { return ptr }

//go:linkname _Cgo_always_false runtime.cgoAlwaysFalse
var _Cgo_always_false bool
//go:linkname _Cgo_use runtime.cgoUse
func _Cgo_use(interface{})
//go:linkname _Cgo_keepalive runtime.cgoKeepAlive
//go:noescape
func _Cgo_keepalive(interface{})
//go:linkname _Cgo_no_callback runtime.cgoNoCallback
func _Cgo_no_callback(bool)
type _Ctype__Bool bool

type _Ctype__GoString_ string

type _Ctype___int32_t = _Ctype_int

type _Ctype___int64_t = _Ctype_long

type _Ctype___uint32_t = _Ctype_uint

type _Ctype___uint64_t = _Ctype_ulong

type _Ctype_bool = _Ctype__Bool

type _Ctype_cchar_t = _Ctype_char

type _Ctype_cgx_device = _Ctype_cgx_handle

type _Ctype_cgx_error = _Ctype_cgx_handle

type _Ctype_cgx_function = _Ctype_cgx_handle

type _Ctype_cgx_handle = _Ctype_uint64_t

type _Ctype_cgx_host_buffer = _Ctype_cgx_handle

type _Ctype_cgx_interface = _Ctype_cgx_handle

type _Ctype_cgx_package = _Ctype_cgx_handle

type _Ctype_cgx_package_ir = _Ctype_cgx_handle

type _Ctype_cgx_runtime = _Ctype_cgx_handle

type _Ctype_cgx_shape = _Ctype_cgx_handle

type _Ctype_cgx_struct = _Ctype_cgx_handle

type _Ctype_cgx_value = _Ctype_cgx_handle

type _Ctype_char int8

type _Ctype_cint64_t = _Ctype_int64_t

type _Ctype_cvoid_t = _Ctype_void

type _Ctype_double float64

type _Ctype_enum_cgx_value_kind = uint32

type _Ctype_float float32

type _Ctype_int int32

type _Ctype_int32_t = _Ctype___int32_t

type _Ctype_int64_t = _Ctype___int64_t

type _Ctype_intgo = _Ctype_ptrdiff_t

type _Ctype_long int64

type _Ctype_ptrdiff_t = _Ctype_long

type _Ctype_struct_cgx_device_get_result struct {
	device	_Ctype_cgx_device
	error	_Ctype_cgx_error
}

type _Ctype_struct_cgx_function_find_result struct {
	function	_Ctype_cgx_function
	error		_Ctype_cgx_error
}

type _Ctype_struct_cgx_function_run_result struct {
	values		*_Ctype_cgx_value
	value_size	_Ctype_uint32_t
	error		_Ctype_cgx_error
}

type _Ctype_struct_cgx_function_signature_element struct {
	name	*_Ctype_char
	kind	uint32
	_	[4]byte
}

type _Ctype_struct_cgx_function_signature_result struct {
	parameter	*_Ctype_struct_cgx_function_signature_element
	parameter_size	_Ctype_uint32_t
	result		*_Ctype_struct_cgx_function_signature_element
	result_size	_Ctype_uint32_t
	error		_Ctype_cgx_error
}

type _Ctype_struct_cgx_interface_find_result struct {
	iface	_Ctype_cgx_interface
	error	_Ctype_cgx_error
}

type _Ctype_struct_cgx_list_functions_result struct {
	funcs		*_Ctype_cgx_function
	num_functions	_Ctype_int
	error		_Ctype_cgx_error
}

type _Ctype_struct_cgx_package_ir_load_result struct {
	_package	_Ctype_cgx_package_ir
	error		_Ctype_cgx_error
}

type _Ctype_struct_cgx_shape_axes_result struct {
	axis_lengths	*_Ctype_int64_t
	num_axes	_Ctype_uint32_t
	error		_Ctype_cgx_error
}

type _Ctype_struct_cgx_struct_field_element struct {
	name	*_Ctype_char
	kind	uint32
	_	[4]byte
}

type _Ctype_struct_cgx_struct_field_list_result struct {
	field		*_Ctype_struct_cgx_struct_field_element
	field_size	_Ctype_uint32_t
	error		_Ctype_cgx_error
}

type _Ctype_struct_cgx_value_get_struct_result struct {
	strct	_Ctype_cgx_struct
	error	_Ctype_cgx_error
}

type _Ctype_struct_cgx_value_host_buffer_result struct {
	buffer	_Ctype_cgx_host_buffer
	error	_Ctype_cgx_error
}

type _Ctype_struct_cgx_value_new_result struct {
	value	_Ctype_cgx_value
	error	_Ctype_cgx_error
}

type _Ctype_uint uint32

type _Ctype_uint32_t = _Ctype___uint32_t

type _Ctype_uint64_t = _Ctype___uint64_t

type _Ctype_ulong uint64

type _Ctype_void [0]byte

//go:linkname _cgo_runtime_cgocall runtime.cgocall
func _cgo_runtime_cgocall(unsafe.Pointer, uintptr) int32

//go:linkname _cgoCheckPointer runtime.cgoCheckPointer
//go:noescape
func _cgoCheckPointer(interface{}, interface{})

//go:linkname _cgoCheckResult runtime.cgoCheckResult
//go:noescape
func _cgoCheckResult(interface{})
const _Ciconst_CGX_ARRAY = 0x9
const _Ciconst_CGX_BFLOAT16 = 0x2
const _Ciconst_CGX_BOOL = 0x1
const _Ciconst_CGX_FLOAT32 = 0x3
const _Ciconst_CGX_FLOAT64 = 0x4
const _Ciconst_CGX_INT32 = 0x5
const _Ciconst_CGX_INT64 = 0x6
const _Ciconst_CGX_INVALID = 0x0
const _Ciconst_CGX_SLICE = 0xa
const _Ciconst_CGX_STRUCT = 0xb
const _Ciconst_CGX_UINT32 = 0x7
const _Ciconst_CGX_UINT64 = 0x8


// CString converts the Go string s to a C string.
//
// The C string is allocated in the C heap using malloc.
// It is the caller's responsibility to arrange for it to be
// freed, such as by calling C.free (be sure to include stdlib.h
// if C.free is needed).
func _Cfunc_CString(s string) *_Ctype_char {
	if len(s)+1 <= 0 {
		panic("string too large")
	}
	p := _cgo_cmalloc(uint64(len(s)+1))
	sliceHeader := struct {
		p   unsafe.Pointer
		len int
		cap int
	}{p, len(s)+1, len(s)+1}
	b := *(*[]byte)(unsafe.Pointer(&sliceHeader))
	copy(b, s)
	b[len(s)] = 0
	return (*_Ctype_char)(p)
}

//go:linkname _cgo_runtime_gostring runtime.gostring
func _cgo_runtime_gostring(*_Ctype_char) string

// GoString converts the C string p into a Go string.
func _Cfunc_GoString(p *_Ctype_char) string {
	return _cgo_runtime_gostring(p)
}
//go:cgo_import_static _cgo_5b999f2b2c28_Cfunc_free
//go:linkname __cgofn__cgo_5b999f2b2c28_Cfunc_free _cgo_5b999f2b2c28_Cfunc_free
var __cgofn__cgo_5b999f2b2c28_Cfunc_free byte
var _cgo_5b999f2b2c28_Cfunc_free = unsafe.Pointer(&__cgofn__cgo_5b999f2b2c28_Cfunc_free)

//go:cgo_unsafe_args
func _Cfunc_free(p0 unsafe.Pointer) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_5b999f2b2c28_Cfunc_free, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_export_dynamic cgx_release_reference
//go:linkname _cgoexp_5b999f2b2c28_cgx_release_reference _cgoexp_5b999f2b2c28_cgx_release_reference
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_release_reference
func _cgoexp_5b999f2b2c28_cgx_release_reference(a *struct {
		p0 _Ctype_cgx_handle
		r0 uintptr
	}) {
	a.r0 = cgx_release_reference(a.p0)
	_cgoCheckResult(a.r0)
}
//go:cgo_export_dynamic cgx_release_references
//go:linkname _cgoexp_5b999f2b2c28_cgx_release_references _cgoexp_5b999f2b2c28_cgx_release_references
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_release_references
func _cgoexp_5b999f2b2c28_cgx_release_references(a *struct {
		p0 *_Ctype_cgx_handle
		p1 _Ctype_uint32_t
		r0 uintptr
	}) {
	a.r0 = cgx_release_references(a.p0, a.p1)
	_cgoCheckResult(a.r0)
}
//go:cgo_export_dynamic cgx_handle_count
//go:linkname _cgoexp_5b999f2b2c28_cgx_handle_count _cgoexp_5b999f2b2c28_cgx_handle_count
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_handle_count
func _cgoexp_5b999f2b2c28_cgx_handle_count(a *struct {
		r0 _Ctype_int64_t
	}) {
	a.r0 = cgx_handle_count()
}
//go:cgo_export_dynamic cgx_handle_dump
//go:linkname _cgoexp_5b999f2b2c28_cgx_handle_dump _cgoexp_5b999f2b2c28_cgx_handle_dump
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_handle_dump
func _cgoexp_5b999f2b2c28_cgx_handle_dump(a *struct {
		r0 *_Ctype_cchar_t
	}) {
	a.r0 = cgx_handle_dump()
	_cgoCheckResult(a.r0)
}
//go:cgo_export_dynamic cgx_error_message
//go:linkname _cgoexp_5b999f2b2c28_cgx_error_message _cgoexp_5b999f2b2c28_cgx_error_message
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_error_message
func _cgoexp_5b999f2b2c28_cgx_error_message(a *struct {
		p0 _Ctype_cgx_error
		r0 *_Ctype_cchar_t
	}) {
	a.r0 = cgx_error_message(a.p0)
	_cgoCheckResult(a.r0)
}
//go:cgo_export_dynamic cgx_error_debug_message
//go:linkname _cgoexp_5b999f2b2c28_cgx_error_debug_message _cgoexp_5b999f2b2c28_cgx_error_debug_message
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_error_debug_message
func _cgoexp_5b999f2b2c28_cgx_error_debug_message(a *struct {
		p0 _Ctype_cgx_error
		r0 *_Ctype_cchar_t
	}) {
	a.r0 = cgx_error_debug_message(a.p0)
	_cgoCheckResult(a.r0)
}
//go:cgo_export_dynamic cgx_device_get
//go:linkname _cgoexp_5b999f2b2c28_cgx_device_get _cgoexp_5b999f2b2c28_cgx_device_get
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_device_get
func _cgoexp_5b999f2b2c28_cgx_device_get(a *struct {
		p0 _Ctype_cgx_runtime
		p1 int
		r0 _Ctype_struct_cgx_device_get_result
	}) {
	a.r0 = cgx_device_get(a.p0, a.p1)
}
//go:cgo_export_dynamic cgx_device_get_runtime
//go:linkname _cgoexp_5b999f2b2c28_cgx_device_get_runtime _cgoexp_5b999f2b2c28_cgx_device_get_runtime
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_device_get_runtime
func _cgoexp_5b999f2b2c28_cgx_device_get_runtime(a *struct {
		p0 _Ctype_cgx_device
		r0 _Ctype_cgx_runtime
	}) {
	a.r0 = cgx_device_get_runtime(a.p0)
}
//go:cgo_export_dynamic cgx_package_ir_load
//go:linkname _cgoexp_5b999f2b2c28_cgx_package_ir_load _cgoexp_5b999f2b2c28_cgx_package_ir_load
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_package_ir_load
func _cgoexp_5b999f2b2c28_cgx_package_ir_load(a *struct {
		p0 _Ctype_cgx_runtime
		p1 *_Ctype_cchar_t
		r0 _Ctype_struct_cgx_package_ir_load_result
	}) {
	a.r0 = cgx_package_ir_load(a.p0, a.p1)
}
//go:cgo_export_dynamic cgx_package_ir_build_for
//go:linkname _cgoexp_5b999f2b2c28_cgx_package_ir_build_for _cgoexp_5b999f2b2c28_cgx_package_ir_build_for
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_package_ir_build_for
func _cgoexp_5b999f2b2c28_cgx_package_ir_build_for(a *struct {
		p0 _Ctype_cgx_package_ir
		p1 _Ctype_cgx_device
		r0 _Ctype_cgx_package
	}) {
	a.r0 = cgx_package_ir_build_for(a.p0, a.p1)
}
//go:cgo_export_dynamic cgx_package_ir_name
//go:linkname _cgoexp_5b999f2b2c28_cgx_package_ir_name _cgoexp_5b999f2b2c28_cgx_package_ir_name
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_package_ir_name
func _cgoexp_5b999f2b2c28_cgx_package_ir_name(a *struct {
		p0 _Ctype_cgx_package_ir
		r0 *_Ctype_cchar_t
	}) {
	a.r0 = cgx_package_ir_name(a.p0)
	_cgoCheckResult(a.r0)
}
//go:cgo_export_dynamic cgx_package_ir_fullname
//go:linkname _cgoexp_5b999f2b2c28_cgx_package_ir_fullname _cgoexp_5b999f2b2c28_cgx_package_ir_fullname
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_package_ir_fullname
func _cgoexp_5b999f2b2c28_cgx_package_ir_fullname(a *struct {
		p0 _Ctype_cgx_package_ir
		r0 *_Ctype_cchar_t
	}) {
	a.r0 = cgx_package_ir_fullname(a.p0)
	_cgoCheckResult(a.r0)
}
//go:cgo_export_dynamic cgx_package_list_functions
//go:linkname _cgoexp_5b999f2b2c28_cgx_package_list_functions _cgoexp_5b999f2b2c28_cgx_package_list_functions
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_package_list_functions
func _cgoexp_5b999f2b2c28_cgx_package_list_functions(a *struct {
		p0 _Ctype_cgx_package
		r0 _Ctype_struct_cgx_list_functions_result
	}) {
	a.r0 = cgx_package_list_functions(a.p0)
	_cgoCheckResult(a.r0)
}
//go:cgo_export_dynamic cgx_package_get_ir
//go:linkname _cgoexp_5b999f2b2c28_cgx_package_get_ir _cgoexp_5b999f2b2c28_cgx_package_get_ir
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_package_get_ir
func _cgoexp_5b999f2b2c28_cgx_package_get_ir(a *struct {
		p0 _Ctype_cgx_package
		r0 _Ctype_cgx_package_ir
	}) {
	a.r0 = cgx_package_get_ir(a.p0)
}
//go:cgo_export_dynamic cgx_free_list_functions_result
//go:linkname _cgoexp_5b999f2b2c28_cgx_free_list_functions_result _cgoexp_5b999f2b2c28_cgx_free_list_functions_result
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_free_list_functions_result
func _cgoexp_5b999f2b2c28_cgx_free_list_functions_result(a *struct {
		p0 *_Ctype_struct_cgx_list_functions_result
	}) {
	cgx_free_list_functions_result(a.p0)
}
//go:cgo_export_dynamic cgx_interface_find
//go:linkname _cgoexp_5b999f2b2c28_cgx_interface_find _cgoexp_5b999f2b2c28_cgx_interface_find
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_interface_find
func _cgoexp_5b999f2b2c28_cgx_interface_find(a *struct {
		p0 _Ctype_cgx_package
		p1 *_Ctype_cchar_t
		r0 _Ctype_struct_cgx_interface_find_result
	}) {
	a.r0 = cgx_interface_find(a.p0, a.p1)
}
//go:cgo_export_dynamic cgx_function_find
//go:linkname _cgoexp_5b999f2b2c28_cgx_function_find _cgoexp_5b999f2b2c28_cgx_function_find
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_function_find
func _cgoexp_5b999f2b2c28_cgx_function_find(a *struct {
		p0 _Ctype_cgx_package
		p1 *_Ctype_cchar_t
		r0 _Ctype_struct_cgx_function_find_result
	}) {
	a.r0 = cgx_function_find(a.p0, a.p1)
}
//go:cgo_export_dynamic cgx_function_run
//go:linkname _cgoexp_5b999f2b2c28_cgx_function_run _cgoexp_5b999f2b2c28_cgx_function_run
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_function_run
func _cgoexp_5b999f2b2c28_cgx_function_run(a *struct {
		p0 _Ctype_cgx_function
		p1 _Ctype_cgx_value
		p2 _Ctype_int
		p3 *_Ctype_cgx_value
		r0 _Ctype_struct_cgx_function_run_result
	}) {
	a.r0 = cgx_function_run(a.p0, a.p1, a.p2, a.p3)
	_cgoCheckResult(a.r0)
}
//go:cgo_export_dynamic cgx_function_name
//go:linkname _cgoexp_5b999f2b2c28_cgx_function_name _cgoexp_5b999f2b2c28_cgx_function_name
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_function_name
func _cgoexp_5b999f2b2c28_cgx_function_name(a *struct {
		p0 _Ctype_cgx_function
		r0 *_Ctype_cchar_t
	}) {
	a.r0 = cgx_function_name(a.p0)
	_cgoCheckResult(a.r0)
}
//go:cgo_export_dynamic cgx_function_doc
//go:linkname _cgoexp_5b999f2b2c28_cgx_function_doc _cgoexp_5b999f2b2c28_cgx_function_doc
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_function_doc
func _cgoexp_5b999f2b2c28_cgx_function_doc(a *struct {
		p0 _Ctype_cgx_function
		r0 *_Ctype_cchar_t
	}) {
	a.r0 = cgx_function_doc(a.p0)
	_cgoCheckResult(a.r0)
}
//go:cgo_export_dynamic cgx_function_signature
//go:linkname _cgoexp_5b999f2b2c28_cgx_function_signature _cgoexp_5b999f2b2c28_cgx_function_signature
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_function_signature
func _cgoexp_5b999f2b2c28_cgx_function_signature(a *struct {
		p0 _Ctype_cgx_function
		r0 _Ctype_struct_cgx_function_signature_result
	}) {
	a.r0 = cgx_function_signature(a.p0)
	_cgoCheckResult(a.r0)
}
//go:cgo_export_dynamic cgx_free_function_signature_result
//go:linkname _cgoexp_5b999f2b2c28_cgx_free_function_signature_result _cgoexp_5b999f2b2c28_cgx_free_function_signature_result
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_free_function_signature_result
func _cgoexp_5b999f2b2c28_cgx_free_function_signature_result(a *struct {
		p0 *_Ctype_struct_cgx_function_signature_result
	}) {
	cgx_free_function_signature_result(a.p0)
}
//go:cgo_export_dynamic cgx_function_num_params
//go:linkname _cgoexp_5b999f2b2c28_cgx_function_num_params _cgoexp_5b999f2b2c28_cgx_function_num_params
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_function_num_params
func _cgoexp_5b999f2b2c28_cgx_function_num_params(a *struct {
		p0 _Ctype_cgx_function
		r0 int
	}) {
	a.r0 = cgx_function_num_params(a.p0)
}
//go:cgo_export_dynamic cgx_function_param_dtype
//go:linkname _cgoexp_5b999f2b2c28_cgx_function_param_dtype _cgoexp_5b999f2b2c28_cgx_function_param_dtype
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_function_param_dtype
func _cgoexp_5b999f2b2c28_cgx_function_param_dtype(a *struct {
		p0 _Ctype_cgx_function
		p1 int
		r0 _Ctype_enum_cgx_value_kind
	}) {
	a.r0 = cgx_function_param_dtype(a.p0, a.p1)
}
//go:cgo_export_dynamic cgx_free_function_run_result
//go:linkname _cgoexp_5b999f2b2c28_cgx_free_function_run_result _cgoexp_5b999f2b2c28_cgx_free_function_run_result
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_free_function_run_result
func _cgoexp_5b999f2b2c28_cgx_free_function_run_result(a *struct {
		p0 *_Ctype_struct_cgx_function_run_result
	}) {
	cgx_free_function_run_result(a.p0)
}
//go:cgo_export_dynamic cgx_value_new_bool
//go:linkname _cgoexp_5b999f2b2c28_cgx_value_new_bool _cgoexp_5b999f2b2c28_cgx_value_new_bool
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_value_new_bool
func _cgoexp_5b999f2b2c28_cgx_value_new_bool(a *struct {
		p0 _Ctype_cgx_device
		p1 _Ctype_bool
		r0 _Ctype_struct_cgx_value_new_result
	}) {
	a.r0 = cgx_value_new_bool(a.p0, a.p1)
}
//go:cgo_export_dynamic cgx_value_new_float32
//go:linkname _cgoexp_5b999f2b2c28_cgx_value_new_float32 _cgoexp_5b999f2b2c28_cgx_value_new_float32
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_value_new_float32
func _cgoexp_5b999f2b2c28_cgx_value_new_float32(a *struct {
		p0 _Ctype_cgx_device
		p1 _Ctype_float
		r0 _Ctype_struct_cgx_value_new_result
	}) {
	a.r0 = cgx_value_new_float32(a.p0, a.p1)
}
//go:cgo_export_dynamic cgx_value_new_float64
//go:linkname _cgoexp_5b999f2b2c28_cgx_value_new_float64 _cgoexp_5b999f2b2c28_cgx_value_new_float64
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_value_new_float64
func _cgoexp_5b999f2b2c28_cgx_value_new_float64(a *struct {
		p0 _Ctype_cgx_device
		p1 _Ctype_double
		r0 _Ctype_struct_cgx_value_new_result
	}) {
	a.r0 = cgx_value_new_float64(a.p0, a.p1)
}
//go:cgo_export_dynamic cgx_value_new_int32
//go:linkname _cgoexp_5b999f2b2c28_cgx_value_new_int32 _cgoexp_5b999f2b2c28_cgx_value_new_int32
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_value_new_int32
func _cgoexp_5b999f2b2c28_cgx_value_new_int32(a *struct {
		p0 _Ctype_cgx_device
		p1 _Ctype_int32_t
		r0 _Ctype_struct_cgx_value_new_result
	}) {
	a.r0 = cgx_value_new_int32(a.p0, a.p1)
}
//go:cgo_export_dynamic cgx_value_new_int64
//go:linkname _cgoexp_5b999f2b2c28_cgx_value_new_int64 _cgoexp_5b999f2b2c28_cgx_value_new_int64
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_value_new_int64
func _cgoexp_5b999f2b2c28_cgx_value_new_int64(a *struct {
		p0 _Ctype_cgx_device
		p1 _Ctype_int64_t
		r0 _Ctype_struct_cgx_value_new_result
	}) {
	a.r0 = cgx_value_new_int64(a.p0, a.p1)
}
//go:cgo_export_dynamic cgx_value_new_uint32
//go:linkname _cgoexp_5b999f2b2c28_cgx_value_new_uint32 _cgoexp_5b999f2b2c28_cgx_value_new_uint32
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_value_new_uint32
func _cgoexp_5b999f2b2c28_cgx_value_new_uint32(a *struct {
		p0 _Ctype_cgx_device
		p1 _Ctype_uint32_t
		r0 _Ctype_struct_cgx_value_new_result
	}) {
	a.r0 = cgx_value_new_uint32(a.p0, a.p1)
}
//go:cgo_export_dynamic cgx_value_new_uint64
//go:linkname _cgoexp_5b999f2b2c28_cgx_value_new_uint64 _cgoexp_5b999f2b2c28_cgx_value_new_uint64
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_value_new_uint64
func _cgoexp_5b999f2b2c28_cgx_value_new_uint64(a *struct {
		p0 _Ctype_cgx_device
		p1 _Ctype_uint64_t
		r0 _Ctype_struct_cgx_value_new_result
	}) {
	a.r0 = cgx_value_new_uint64(a.p0, a.p1)
}
//go:cgo_export_dynamic cgx_value_send
//go:linkname _cgoexp_5b999f2b2c28_cgx_value_send _cgoexp_5b999f2b2c28_cgx_value_send
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_value_send
func _cgoexp_5b999f2b2c28_cgx_value_send(a *struct {
		p0 _Ctype_cgx_device
		p1 _Ctype_cgx_shape
		p2 *_Ctype_cvoid_t
		p3 _Ctype_uint64_t
		r0 _Ctype_struct_cgx_value_new_result
	}) {
	a.r0 = cgx_value_send(a.p0, a.p1, a.p2, a.p3)
}
//go:cgo_export_dynamic cgx_value_kind_of
//go:linkname _cgoexp_5b999f2b2c28_cgx_value_kind_of _cgoexp_5b999f2b2c28_cgx_value_kind_of
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_value_kind_of
func _cgoexp_5b999f2b2c28_cgx_value_kind_of(a *struct {
		p0 _Ctype_cgx_value
		r0 _Ctype_enum_cgx_value_kind
	}) {
	a.r0 = cgx_value_kind_of(a.p0)
}
//go:cgo_export_dynamic cgx_value_shape
//go:linkname _cgoexp_5b999f2b2c28_cgx_value_shape _cgoexp_5b999f2b2c28_cgx_value_shape
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_value_shape
func _cgoexp_5b999f2b2c28_cgx_value_shape(a *struct {
		p0 _Ctype_cgx_value
		r0 _Ctype_cgx_shape
	}) {
	a.r0 = cgx_value_shape(a.p0)
}
//go:cgo_export_dynamic cgx_value_get_bool
//go:linkname _cgoexp_5b999f2b2c28_cgx_value_get_bool _cgoexp_5b999f2b2c28_cgx_value_get_bool
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_value_get_bool
func _cgoexp_5b999f2b2c28_cgx_value_get_bool(a *struct {
		p0 _Ctype_cgx_value
		r0 _Ctype_bool
	}) {
	a.r0 = cgx_value_get_bool(a.p0)
}
//go:cgo_export_dynamic cgx_value_get_float32
//go:linkname _cgoexp_5b999f2b2c28_cgx_value_get_float32 _cgoexp_5b999f2b2c28_cgx_value_get_float32
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_value_get_float32
func _cgoexp_5b999f2b2c28_cgx_value_get_float32(a *struct {
		p0 _Ctype_cgx_value
		r0 _Ctype_float
	}) {
	a.r0 = cgx_value_get_float32(a.p0)
}
//go:cgo_export_dynamic cgx_value_get_float64
//go:linkname _cgoexp_5b999f2b2c28_cgx_value_get_float64 _cgoexp_5b999f2b2c28_cgx_value_get_float64
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_value_get_float64
func _cgoexp_5b999f2b2c28_cgx_value_get_float64(a *struct {
		p0 _Ctype_cgx_value
		r0 _Ctype_double
	}) {
	a.r0 = cgx_value_get_float64(a.p0)
}
//go:cgo_export_dynamic cgx_value_get_int32
//go:linkname _cgoexp_5b999f2b2c28_cgx_value_get_int32 _cgoexp_5b999f2b2c28_cgx_value_get_int32
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_value_get_int32
func _cgoexp_5b999f2b2c28_cgx_value_get_int32(a *struct {
		p0 _Ctype_cgx_value
		r0 _Ctype_int32_t
	}) {
	a.r0 = cgx_value_get_int32(a.p0)
}
//go:cgo_export_dynamic cgx_value_get_int64
//go:linkname _cgoexp_5b999f2b2c28_cgx_value_get_int64 _cgoexp_5b999f2b2c28_cgx_value_get_int64
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_value_get_int64
func _cgoexp_5b999f2b2c28_cgx_value_get_int64(a *struct {
		p0 _Ctype_cgx_value
		r0 _Ctype_int64_t
	}) {
	a.r0 = cgx_value_get_int64(a.p0)
}
//go:cgo_export_dynamic cgx_value_get_uint32
//go:linkname _cgoexp_5b999f2b2c28_cgx_value_get_uint32 _cgoexp_5b999f2b2c28_cgx_value_get_uint32
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_value_get_uint32
func _cgoexp_5b999f2b2c28_cgx_value_get_uint32(a *struct {
		p0 _Ctype_cgx_value
		r0 _Ctype_uint32_t
	}) {
	a.r0 = cgx_value_get_uint32(a.p0)
}
//go:cgo_export_dynamic cgx_value_get_uint64
//go:linkname _cgoexp_5b999f2b2c28_cgx_value_get_uint64 _cgoexp_5b999f2b2c28_cgx_value_get_uint64
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_value_get_uint64
func _cgoexp_5b999f2b2c28_cgx_value_get_uint64(a *struct {
		p0 _Ctype_cgx_value
		r0 _Ctype_uint64_t
	}) {
	a.r0 = cgx_value_get_uint64(a.p0)
}
//go:cgo_export_dynamic cgx_value_host_buffer
//go:linkname _cgoexp_5b999f2b2c28_cgx_value_host_buffer _cgoexp_5b999f2b2c28_cgx_value_host_buffer
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_value_host_buffer
func _cgoexp_5b999f2b2c28_cgx_value_host_buffer(a *struct {
		p0 _Ctype_cgx_value
		r0 _Ctype_struct_cgx_value_host_buffer_result
	}) {
	a.r0 = cgx_value_host_buffer(a.p0)
}
//go:cgo_export_dynamic cgx_value_get_struct
//go:linkname _cgoexp_5b999f2b2c28_cgx_value_get_struct _cgoexp_5b999f2b2c28_cgx_value_get_struct
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_value_get_struct
func _cgoexp_5b999f2b2c28_cgx_value_get_struct(a *struct {
		p0 _Ctype_cgx_value
		r0 _Ctype_struct_cgx_value_get_struct_result
	}) {
	a.r0 = cgx_value_get_struct(a.p0)
}
//go:cgo_export_dynamic cgx_value_get_interface_type
//go:linkname _cgoexp_5b999f2b2c28_cgx_value_get_interface_type _cgoexp_5b999f2b2c28_cgx_value_get_interface_type
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_value_get_interface_type
func _cgoexp_5b999f2b2c28_cgx_value_get_interface_type(a *struct {
		p0 _Ctype_cgx_device
		p1 _Ctype_cgx_value
		r0 _Ctype_cgx_interface
	}) {
	a.r0 = cgx_value_get_interface_type(a.p0, a.p1)
}
//go:cgo_export_dynamic cgx_value_string
//go:linkname _cgoexp_5b999f2b2c28_cgx_value_string _cgoexp_5b999f2b2c28_cgx_value_string
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_value_string
func _cgoexp_5b999f2b2c28_cgx_value_string(a *struct {
		p0 _Ctype_cgx_value
		r0 *_Ctype_cchar_t
	}) {
	a.r0 = cgx_value_string(a.p0)
	_cgoCheckResult(a.r0)
}
//go:cgo_export_dynamic cgx_shape_new
//go:linkname _cgoexp_5b999f2b2c28_cgx_shape_new _cgoexp_5b999f2b2c28_cgx_shape_new
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_shape_new
func _cgoexp_5b999f2b2c28_cgx_shape_new(a *struct {
		p0 _Ctype_enum_cgx_value_kind
		p1 *_Ctype_cint64_t
		p2 _Ctype_int
		r0 _Ctype_cgx_shape
	}) {
	a.r0 = cgx_shape_new(a.p0, a.p1, a.p2)
}
//go:cgo_export_dynamic cgx_shape_axes
//go:linkname _cgoexp_5b999f2b2c28_cgx_shape_axes _cgoexp_5b999f2b2c28_cgx_shape_axes
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_shape_axes
func _cgoexp_5b999f2b2c28_cgx_shape_axes(a *struct {
		p0 _Ctype_cgx_shape
		r0 _Ctype_struct_cgx_shape_axes_result
	}) {
	a.r0 = cgx_shape_axes(a.p0)
	_cgoCheckResult(a.r0)
}
//go:cgo_export_dynamic cgx_free_shape_axes_result
//go:linkname _cgoexp_5b999f2b2c28_cgx_free_shape_axes_result _cgoexp_5b999f2b2c28_cgx_free_shape_axes_result
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_free_shape_axes_result
func _cgoexp_5b999f2b2c28_cgx_free_shape_axes_result(a *struct {
		p0 *_Ctype_struct_cgx_shape_axes_result
	}) {
	cgx_free_shape_axes_result(a.p0)
}
//go:cgo_export_dynamic cgx_shape_size
//go:linkname _cgoexp_5b999f2b2c28_cgx_shape_size _cgoexp_5b999f2b2c28_cgx_shape_size
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_shape_size
func _cgoexp_5b999f2b2c28_cgx_shape_size(a *struct {
		p0 _Ctype_cgx_shape
		r0 _Ctype_int
	}) {
	a.r0 = cgx_shape_size(a.p0)
}
//go:cgo_export_dynamic cgx_shape_element_kind
//go:linkname _cgoexp_5b999f2b2c28_cgx_shape_element_kind _cgoexp_5b999f2b2c28_cgx_shape_element_kind
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_shape_element_kind
func _cgoexp_5b999f2b2c28_cgx_shape_element_kind(a *struct {
		p0 _Ctype_cgx_shape
		r0 _Ctype_enum_cgx_value_kind
	}) {
	a.r0 = cgx_shape_element_kind(a.p0)
}
//go:cgo_export_dynamic cgx_host_buffer_acquire_data
//go:linkname _cgoexp_5b999f2b2c28_cgx_host_buffer_acquire_data _cgoexp_5b999f2b2c28_cgx_host_buffer_acquire_data
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_host_buffer_acquire_data
func _cgoexp_5b999f2b2c28_cgx_host_buffer_acquire_data(a *struct {
		p0 _Ctype_cgx_host_buffer
		r0 *_Ctype_char
	}) {
	a.r0 = cgx_host_buffer_acquire_data(a.p0)
	_cgoCheckResult(a.r0)
}
//go:cgo_export_dynamic cgx_host_buffer_release_data
//go:linkname _cgoexp_5b999f2b2c28_cgx_host_buffer_release_data _cgoexp_5b999f2b2c28_cgx_host_buffer_release_data
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_host_buffer_release_data
func _cgoexp_5b999f2b2c28_cgx_host_buffer_release_data(a *struct {
		p0 _Ctype_cgx_host_buffer
		p1 *_Ctype_char
	}) {
	cgx_host_buffer_release_data(a.p0, a.p1)
}
//go:cgo_export_dynamic cgx_struct_field_get
//go:linkname _cgoexp_5b999f2b2c28_cgx_struct_field_get _cgoexp_5b999f2b2c28_cgx_struct_field_get
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_struct_field_get
func _cgoexp_5b999f2b2c28_cgx_struct_field_get(a *struct {
		p0 _Ctype_cgx_struct
		p1 *_Ctype_cchar_t
		r0 _Ctype_struct_cgx_value_new_result
	}) {
	a.r0 = cgx_struct_field_get(a.p0, a.p1)
}
//go:cgo_export_dynamic cgx_struct_field_set
//go:linkname _cgoexp_5b999f2b2c28_cgx_struct_field_set _cgoexp_5b999f2b2c28_cgx_struct_field_set
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_struct_field_set
func _cgoexp_5b999f2b2c28_cgx_struct_field_set(a *struct {
		p0 _Ctype_cgx_struct
		p1 *_Ctype_cchar_t
		p2 _Ctype_cgx_value
		r0 _Ctype_cgx_error
	}) {
	a.r0 = cgx_struct_field_set(a.p0, a.p1, a.p2)
}
//go:cgo_export_dynamic cgx_struct_field_list
//go:linkname _cgoexp_5b999f2b2c28_cgx_struct_field_list _cgoexp_5b999f2b2c28_cgx_struct_field_list
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_struct_field_list
func _cgoexp_5b999f2b2c28_cgx_struct_field_list(a *struct {
		p0 _Ctype_cgx_struct
		r0 _Ctype_struct_cgx_struct_field_list_result
	}) {
	a.r0 = cgx_struct_field_list(a.p0)
	_cgoCheckResult(a.r0)
}
//go:cgo_export_dynamic cgx_free_struct_field_list_result
//go:linkname _cgoexp_5b999f2b2c28_cgx_free_struct_field_list_result _cgoexp_5b999f2b2c28_cgx_free_struct_field_list_result
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_free_struct_field_list_result
func _cgoexp_5b999f2b2c28_cgx_free_struct_field_list_result(a *struct {
		p0 *_Ctype_struct_cgx_struct_field_list_result
	}) {
	cgx_free_struct_field_list_result(a.p0)
}
//go:cgo_export_dynamic cgx_interface_method_find
//go:linkname _cgoexp_5b999f2b2c28_cgx_interface_method_find _cgoexp_5b999f2b2c28_cgx_interface_method_find
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_interface_method_find
func _cgoexp_5b999f2b2c28_cgx_interface_method_find(a *struct {
		p0 _Ctype_cgx_interface
		p1 *_Ctype_cchar_t
		r0 _Ctype_struct_cgx_function_find_result
	}) {
	a.r0 = cgx_interface_method_find(a.p0, a.p1)
}
//go:cgo_export_dynamic cgx_interface_name
//go:linkname _cgoexp_5b999f2b2c28_cgx_interface_name _cgoexp_5b999f2b2c28_cgx_interface_name
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_interface_name
func _cgoexp_5b999f2b2c28_cgx_interface_name(a *struct {
		p0 _Ctype_cgx_interface
		r0 *_Ctype_cchar_t
	}) {
	a.r0 = cgx_interface_name(a.p0)
	_cgoCheckResult(a.r0)
}
//go:cgo_export_dynamic cgx_interface_package_name
//go:linkname _cgoexp_5b999f2b2c28_cgx_interface_package_name _cgoexp_5b999f2b2c28_cgx_interface_package_name
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_interface_package_name
func _cgoexp_5b999f2b2c28_cgx_interface_package_name(a *struct {
		p0 _Ctype_cgx_interface
		r0 *_Ctype_cchar_t
	}) {
	a.r0 = cgx_interface_package_name(a.p0)
	_cgoCheckResult(a.r0)
}
//go:cgo_export_dynamic cgx_interface_list_methods
//go:linkname _cgoexp_5b999f2b2c28_cgx_interface_list_methods _cgoexp_5b999f2b2c28_cgx_interface_list_methods
//go:cgo_export_static _cgoexp_5b999f2b2c28_cgx_interface_list_methods
func _cgoexp_5b999f2b2c28_cgx_interface_list_methods(a *struct {
		p0 _Ctype_cgx_interface
		r0 _Ctype_struct_cgx_list_functions_result
	}) {
	a.r0 = cgx_interface_list_methods(a.p0)
	_cgoCheckResult(a.r0)
}

//go:cgo_import_static _cgo_5b999f2b2c28_Cfunc__Cmalloc
//go:linkname __cgofn__cgo_5b999f2b2c28_Cfunc__Cmalloc _cgo_5b999f2b2c28_Cfunc__Cmalloc
var __cgofn__cgo_5b999f2b2c28_Cfunc__Cmalloc byte
var _cgo_5b999f2b2c28_Cfunc__Cmalloc = unsafe.Pointer(&__cgofn__cgo_5b999f2b2c28_Cfunc__Cmalloc)

//go:linkname runtime_throw runtime.throw
func runtime_throw(string)

//go:cgo_unsafe_args
func _cgo_cmalloc(p0 uint64) (r1 unsafe.Pointer) {
	_cgo_runtime_cgocall(_cgo_5b999f2b2c28_Cfunc__Cmalloc, uintptr(unsafe.Pointer(&p0)))
	if r1 == nil {
		runtime_throw("runtime: C malloc failed")
	}
	return
}
