// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package pkgvars_go_gx are Go bindings to the GX package:
// github.com/gx-org/gx/tests/bindings/pkgvars.
//
// Automatically generated by
// gx/golang/binder/gobindings/bindings.go.tmpl.
package pkgvars_go_gx

import (
	"fmt"
	"reflect"
	"strings"

	"github.com/gx-org/backend/platform"
	"github.com/gx-org/gx/api"
	"github.com/gx-org/gx/api/options"
	"github.com/gx-org/gx/api/trace"
	"github.com/gx-org/gx/api/tracer"
	"github.com/gx-org/gx/api/values"
	"github.com/gx-org/gx/build/ir"
	"github.com/gx-org/gx/golang/binder/gobindings/types"
	_ "github.com/gx-org/gx/tests/bindings/pkgvars"
	"github.com/pkg/errors"
)

// Force some package dependencies.
var (
	_ = fmt.Println
	_ = strings.Compare
	_ = reflect.TypeFor[int]
	_ = values.Struct{}
	_ = errors.Errorf
	_ = types.NewSlice[types.Bridger]
	_ = platform.HostTransfer
)

// PackageIR is the GX package intermediate representation
// built for a given runtime, but not yet for a specific device.
type PackageIR struct {
	Runtime *api.Runtime
	IR      *ir.Package
	Tracer  trace.Callback
}

// Load the GX package for a given backend.
func Load(rtm *api.Runtime) (*PackageIR, error) {
	bpkg, err := rtm.Builder().Build("github.com/gx-org/gx/tests/bindings/pkgvars")
	if err != nil {
		return nil, err
	}
	pkg := &PackageIR{
		Runtime: rtm,
		IR:      bpkg.IR(),
	}

	return pkg, nil
}

// BuildFor loads the GX package github.com/gx-org/gx/tests/bindings/pkgvars
// then returns that package for a given device and options.
func BuildFor(dev *api.Device, options ...options.PackageOptionFactory) (*Package, error) {
	pkg, err := Load(dev.Runtime())
	if err != nil {
		return nil, err
	}
	return pkg.BuildFor(dev, options...), nil
}

// Factory create new instance of types used in the package.
// The compiler associated with the factory defines on what
// device and with which options methods of the instances
// created by the factory are compiled for.
type Factory struct {
	Package *Package
}

// Package is a GX package for a given device.
// Functions and methods are compiled specifically for that device.
type Package struct {
	Package *PackageIR
	Device  *api.Device
	Factory *Factory

	options []options.PackageOption

	ReturnVar1   ReturnVar1
	NewTwiceSize NewTwiceSize
}

// AppendOptions appends options to the compiler.
func (cmpl *Package) AppendOptions(options ...options.PackageOptionFactory) {
	plat := cmpl.Package.Runtime.Backend().Platform()
	for _, opt := range options {
		cmpl.options = append(cmpl.options, opt(plat))
	}
}

// BuildFor returns a package ready to compile for a device and options.
func (pkg *PackageIR) BuildFor(dev *api.Device, options ...options.PackageOptionFactory) *Package {
	c := &Package{
		Package: pkg,
		Device:  dev,
	}
	c.Factory = &Factory{Package: c}
	c.AppendOptions(options...)

	c.ReturnVar1 = ReturnVar1{
		methodBase: methodBase{
			pkg:      c,
			function: c.Package.IR.Decls.Funcs[0],
		},
	}
	c.NewTwiceSize = NewTwiceSize{
		methodBase: methodBase{
			pkg:      c,
			function: c.Package.IR.Decls.Funcs[1],
		},
	}

	return c
}

var Var1 Var1Static

type Var1Static struct {
	value int32
}

func (Var1Static) Set(value int32) options.PackageOptionFactory {
	return func(plat platform.Platform) options.PackageOption {
		hostValue := types.Int32(value)
		return options.PackageVarSetValue{
			Pkg:   "github.com/gx-org/gx/tests/bindings/pkgvars",
			Var:   "Var1",
			Value: hostValue.GXValue(),
		}
	}
}

var Size SizeStatic

type SizeStatic struct {
	value ir.Int
}

func (SizeStatic) Set(value ir.Int) options.PackageOptionFactory {
	return func(plat platform.Platform) options.PackageOption {
		hostValue := types.DefaultInt(value)
		return options.PackageVarSetValue{
			Pkg:   "github.com/gx-org/gx/tests/bindings/pkgvars",
			Var:   "Size",
			Value: hostValue.GXValue(),
		}
	}
}

type methodBase struct {
	pkg      *Package
	function ir.Func
	runner   tracer.CompiledFunc
}

// ReturnVar1 compiles and runs the GX function ReturnVar1 for a device.
// ReturnVar1 returns the value of the static variable Var1
type ReturnVar1 struct {
	methodBase
}

// NewTwiceSize compiles and runs the GX function NewTwiceSize for a device.
// New 1-axis array of size Size.
type NewTwiceSize struct {
	methodBase
}

// Run first compiles ReturnVar1 for a given device and the given arguments.
// Once compiled, the function is then run with these same arguments.
// If the shape of the arguments change, the function will panic.
func (f *ReturnVar1) Run() (_ types.Atom[int32], err error) {
	var args []values.Value = nil
	if f.runner == nil {
		f.runner, err = tracer.Trace(f.pkg.Device, f.function.(*ir.FuncDecl), nil, args, f.pkg.options)
		if err != nil {
			return
		}
	}
	var outputs []values.Value
	outputs, err = f.runner.Run(nil, args, f.pkg.Package.Tracer)
	if err != nil {
		return
	}

	out0Value, ok := outputs[0].(values.Array)
	if !ok {
		err = errors.Errorf("cannot cast %T to %s", outputs[0], reflect.TypeFor[*values.DeviceArray]().Name())
		return
	}
	out0 := types.NewAtom[int32](out0Value)

	return out0, nil
}

func (f *ReturnVar1) String() string {
	return fmt.Sprint(f.function)
}

// Run first compiles NewTwiceSize for a given device and the given arguments.
// Once compiled, the function is then run with these same arguments.
// If the shape of the arguments change, the function will panic.
func (f *NewTwiceSize) Run() (_ types.Array[float32], err error) {
	var args []values.Value = nil
	if f.runner == nil {
		f.runner, err = tracer.Trace(f.pkg.Device, f.function.(*ir.FuncDecl), nil, args, f.pkg.options)
		if err != nil {
			return
		}
	}
	var outputs []values.Value
	outputs, err = f.runner.Run(nil, args, f.pkg.Package.Tracer)
	if err != nil {
		return
	}

	out0Value, ok := outputs[0].(values.Array)
	if !ok {
		err = errors.Errorf("cannot cast %T to %s", outputs[0], reflect.TypeFor[*values.DeviceArray]().Name())
		return
	}
	out0 := types.NewArray[float32](out0Value)

	return out0, nil
}

func (f *NewTwiceSize) String() string {
	return fmt.Sprint(f.function)
}
